# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyWeatherApp
  pod 'Alamofire', '~> 5.4'
  pod 'SDWebImage', '~> 5.0'

  target 'MyWeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyWeatherAppUITests' do
    # Pods for testing
  end

end
